Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
    config.vm.define "scriptbox" do |scriptbox|
      scriptbox.vm.box = "centos7"
      scriptbox.vm.hostname = "scriptbox"
      scriptbox.vm.network "private_network", ip: "192.168.56.2"
        scriptbox.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end
    
     config.vm.define "web01" do |web01|
      web01.vm.box = "centos7"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.3"
        web01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end
    end

     config.vm.define "web02" do |web02|
        web02.vm.box = "centos7"
        web02.vm.hostname = "web02"
        web02.vm.network "private_network", ip: "192.168.56.4"
            web02.vm.provider "virtualbox" do |vb|
                vb.memory = "1024"
            end
    end     

    config.vm.define "web03" do |web03|
        web03.vm.box = "ubuntu/xenial64"
        web03.vm.hostname = "web03"
        web03.vm.network "private_network", ip: "192.168.56.5"
    end
end